### ISSUE TITLE
Miért jó a félóránkénti commit? A github-os aktivitás kizöldítése miatt?

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [markkovari/xmas_tree#2]
![image](https://github.com/markkovari/xmas_tree/assets/2386064/bfecaf17-13e5-4a8a-823b-06acf602e3cc)

**Comment by markkovari** [comment]
Ez egy kutatas resze volt: wasm runtimeokkal es kulonbozo agentekkel - schedulerekkel es hosted github runnerekkel.
Es a vegen igy hagytam. Kb ennyi.
